spring:
  application:
    name: CONFIGCLIENT
  cloud:
    consul:
      host: localhost
      port: 8500
  rabbitmq:
    host: 192.168.60.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /    
